[tool.poetry]
name = "yyytdlp-gui"
version = "0.1.0"
description = "my yt-dlp GUI wrapper"
authors = ["yy-tromb <107352731+yy-tromb@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"
packages = [{include = "yyytdlp_gui"}]

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.9.0"
yt-dlp = "^2023.7.6"
asyncio = "^3.4.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
ruff = "^0.0.284"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
